"""Dagster code location for the quant platform.

Registers the bronze → silver → gold data-layer assets, their asset checks,
and any per-strategy assets generated by Task 2.2's RegisterStrategy command.
"""

from __future__ import annotations

from dagster import Definitions

from app.dagster_defs.assets import (
    bronze_synthetic_universe,
    gold_alpha_features,
    gold_row_count_check,
    pit_integrity_check,
    silver_pit_prices,
)
from app.dagster_defs.strategies import all_strategy_assets

defs = Definitions(
    assets=[
        bronze_synthetic_universe,
        silver_pit_prices,
        gold_alpha_features,
        *all_strategy_assets(),
    ],
    asset_checks=[pit_integrity_check, gold_row_count_check],
    jobs=[],
    schedules=[],
    sensors=[],
)

__all__ = ["defs"]
