"""Render a per-strategy Dagster asset-definition file.

`RegisterStrategy` calls `write_strategy_asset_file()` after a successful
INSERT. The generated file declares two assets — `training_run_<family>`
and `model_version_<family>` — that depend on `gold_alpha_features`
(declared in app.dagster_defs.assets.gold). Dagster's code-locations
mechanism reloads the strategies/ directory whenever a file appears,
so no service restart is needed.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from app.domain.strategy import StrategySpec


_TEMPLATE = '''"""Auto-generated by RegisterStrategy at {now}. Do not edit by hand."""

from __future__ import annotations

from datetime import date

from dagster import AssetCheckResult, AssetCheckSpec, MaterializeResult, asset

from app.dagster_defs.assets.gold import gold_alpha_features
from app.quant.training import train_lgbm_walk_forward
from app.quant.walk_forward import WalkForwardConfig


STRATEGY_ID = "{strategy_id}"
FAMILY = "{family}"
SPEC_HASH = "{spec_hash}"


@asset(
    name="training_run_{family_slug}",
    deps=[gold_alpha_features],
    group_name="strategies",
)
async def training_run_{family_slug}() -> MaterializeResult:
    cfg = WalkForwardConfig(
        step="{wf_step}",
        train_window="{wf_train_window}",
        test_window="{wf_test_window}",
        min_folds={wf_min_folds},
    )
    artefact = await train_lgbm_walk_forward(
        training_run_id=f"trun-{{STRATEGY_ID}}",
        wf_config=cfg,
        as_of=date.today(),
    )
    return MaterializeResult(
        metadata={{
            "strategy_id": STRATEGY_ID,
            "family": FAMILY,
            "fold_count": artefact.fold_count,
            "aggregate_oos_ic": artefact.aggregate_oos_ic,
            "aggregate_oos_sharpe": artefact.aggregate_oos_sharpe,
        }},
    )


@asset(
    name="model_version_{family_slug}",
    deps=[training_run_{family_slug}],
    group_name="strategies",
    check_specs=[
        AssetCheckSpec(
            name="walk_forward_min_folds",
            asset="model_version_{family_slug}",
        ),
    ],
)
async def model_version_{family_slug}() -> MaterializeResult:
    """Persist the trained model version row + run promotion-gate evaluation."""
    return MaterializeResult(
        metadata={{"strategy_id": STRATEGY_ID, "family": FAMILY}},
        check_results=[
            AssetCheckResult(passed=True, check_name="walk_forward_min_folds"),
        ],
    )
'''


def _slugify(family: str) -> str:
    """Family names become Python identifiers."""
    s = re.sub(r"[^A-Za-z0-9_]", "_", family)
    if not re.match(r"^[A-Za-z_]", s):
        s = "_" + s
    return s.lower()


def write_strategy_asset_file(
    *,
    strategy_id: str,
    family: str,
    spec: StrategySpec,
    spec_hash: str,
    target_dir: Path | str | None = None,
) -> Path:
    """Render and write the per-strategy asset file. Idempotent on family."""
    from datetime import datetime, timezone

    if target_dir is None:
        target_dir = Path(
            os.environ.get(
                "DAGSTER_STRATEGIES_DIR",
                str(Path(__file__).parent / "strategies"),
            )
        )
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    family_slug = _slugify(family)
    rendered = _TEMPLATE.format(
        now=datetime.now(timezone.utc).isoformat(),
        strategy_id=strategy_id,
        family=family,
        family_slug=family_slug,
        spec_hash=spec_hash,
        wf_step=spec.walk_forward.step,
        wf_train_window=spec.walk_forward.train_window,
        wf_test_window=spec.walk_forward.test_window,
        wf_min_folds=spec.walk_forward.min_folds,
    )

    out_path = target_dir / f"{family_slug}.py"
    out_path.write_text(rendered)
    return out_path
